#!/bin/bash
#SBATCH --time=100:00:00 
#SBATCH -p week-long
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem-per-cpu=512M
#SBATCH -J "bilby_BBH_run"
#SBATCH --mail-user=wilder@montclair.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL

python inject-h0_study.py
